---
- name: Deploy Website from GitHub
  hosts: slaves
  become: true
  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present

    - name: Clone or pull repository
      git:
        repo: "https://github.com/AWS-Re-Start-RDC-KINSHASA-1/tp-6-ci-cd-load-balancer-with-ngnix.git"
        dest: "/var/lib/jenkins/workspace/daddyansible/ansible_project"  # Temporary directory to clone repository

    - name: Copy website contents to /var/www/html
      synchronize:
        src: "/var/lib/jenkins/workspace/daddyansible/ansible_project/index.html"
        dest: "/var/www/html/"
